 -- EX 7
SELECT D.NOME, COUNT(S.ID) AS QTDE
FROM DISCIPLINA D  
LEFT JOIN DISCIPLINAOFERTADA DO ON D.ID = DO.IDDISCIPLINA
LEFT JOIN SOLICITACAOMATRICULA S ON DO.ID = S.IDDOFERTADA 
GROUP BY D.NOME 
ORDER BY D.NOME 


--EX03
SELECT 
	C.NOME,
	DO.SEMESTRE,
	DO.TURMA,
	D.NOME,
	D.ID,
	DO.IDDISCIPLINA
FROM DISCIPLINAOFERTADA DO 
JOIN DISCIPLINA D ON DO.IDDISCIPLINA = D.ID 
JOIN CURSO C ON C.ID = DO.IDCURSO
WHERE D.STATUS = 'ABERTA' AND DO.ANO = 2018
ORDER BY ID;


--4)
SELECT
	 E.TITULO AS ATIVIDADES_NÃO_ENTREGUES,
	 E.STATUS
FROM DISCIPLINAOFERTADA AS DO
INNER JOIN ATIVIDADEVINCULADA AS AV
ON DO.ID = AV.IDDOFERTADA
INNER JOIN ENTREGA AS E 
ON E.IDAVINCULADA = AV.ID
WHERE E.STATUS NOT IN( 'CORRIGIDO' , 'ENTREGUE')

-- EX 8
SELECT A.NOME, 
       (SELECT EN.NOTA FROM ENTREGA EN JOIN ATIVIDADEVINCULADA ATV ON ATV.ID = EN.IDAVINCULADA WHERE EN.IDALUNO = E.IDALUNO AND ATV.IDATIVIDADE = 1 AND ATV.IDPROFESSOR = AV.IDPROFESSOR) AS AC_1,
       (SELECT EN.NOTA FROM ENTREGA EN JOIN ATIVIDADEVINCULADA ATV ON ATV.ID = EN.IDAVINCULADA WHERE EN.IDALUNO = E.IDALUNO AND ATV.IDATIVIDADE = 2 AND ATV.IDPROFESSOR = AV.IDPROFESSOR) AS AC_2,
	   (SELECT EN.NOTA FROM ENTREGA EN JOIN ATIVIDADEVINCULADA ATV ON ATV.ID = EN.IDAVINCULADA WHERE EN.IDALUNO = E.IDALUNO AND ATV.IDATIVIDADE = 3 AND ATV.IDPROFESSOR = AV.IDPROFESSOR) AS AC_3,
	   (SELECT EN.NOTA FROM ENTREGA EN JOIN ATIVIDADEVINCULADA ATV ON ATV.ID = EN.IDAVINCULADA WHERE EN.IDALUNO = E.IDALUNO AND ATV.IDATIVIDADE = 4 AND ATV.IDPROFESSOR = AV.IDPROFESSOR) AS AC_4,
	   (SELECT EN.NOTA FROM ENTREGA EN JOIN ATIVIDADEVINCULADA ATV ON ATV.ID = EN.IDAVINCULADA WHERE EN.IDALUNO = E.IDALUNO AND ATV.IDATIVIDADE = 5 AND ATV.IDPROFESSOR = AV.IDPROFESSOR) AS AC_5,
       (SELECT EN.NOTA FROM ENTREGA EN JOIN ATIVIDADEVINCULADA ATV ON ATV.ID = EN.IDAVINCULADA WHERE EN.IDALUNO = E.IDALUNO AND ATV.IDATIVIDADE = 6 AND ATV.IDPROFESSOR = AV.IDPROFESSOR) AS AC_6,
	   (SELECT EN.NOTA FROM ENTREGA EN JOIN ATIVIDADEVINCULADA ATV ON ATV.ID = EN.IDAVINCULADA WHERE EN.IDALUNO = E.IDALUNO AND ATV.IDATIVIDADE = 7 AND ATV.IDPROFESSOR = AV.IDPROFESSOR) AS AC_7,
	   (SELECT EN.NOTA FROM ENTREGA EN JOIN ATIVIDADEVINCULADA ATV ON ATV.ID = EN.IDAVINCULADA WHERE EN.IDALUNO = E.IDALUNO AND ATV.IDATIVIDADE = 8 AND ATV.IDPROFESSOR = AV.IDPROFESSOR) AS AC_8,
	   (SELECT EN.NOTA FROM ENTREGA EN JOIN ATIVIDADEVINCULADA ATV ON ATV.ID = EN.IDAVINCULADA WHERE EN.IDALUNO = E.IDALUNO AND ATV.IDATIVIDADE = 9 AND ATV.IDPROFESSOR = AV.IDPROFESSOR) AS AC_9,
	   (SELECT EN.NOTA FROM ENTREGA EN JOIN ATIVIDADEVINCULADA ATV ON ATV.ID = EN.IDAVINCULADA WHERE EN.IDALUNO = E.IDALUNO AND ATV.IDATIVIDADE = 10 AND ATV.IDPROFESSOR = AV.IDPROFESSOR) AS AC_10
FROM ENTREGA E  
JOIN ATIVIDADEVINCULADA AV ON AV.ID = E.IDAVINCULADA 
JOIN ALUNO A ON E.IDALUNO = A.ID
WHERE AV.IDPROFESSOR = 18








EXERCICIOS GET SAM

--2)
SELECT DISTINCT A.NOME AS ALUNO,
	   A.RA,
	   D.NOME AS DISCIPLINA,
	   P.NOME AS PROFESSOR
FROM DISCIPLINAOFERTADA AS DO
INNER JOIN DISCIPLINA AS D
ON DO.IDDISCIPLINA = D.ID
INNER JOIN PROFESSOR AS P
ON DO.IDPROFESSOR = P.ID 
INNER JOIN SOLICITACAOMATRICULA AS SM
ON DO.ID = SM.IDDOFERTADA
INNER JOIN ALUNO AS A
ON SM.IDALUNO = A.ID 
WHERE SM.STATUS = 'APROVADA'
ORDER BY A.NOME

--3)
SELECT DISTINCT
	--DO.TURMA,
	D.NOME     AS NOME_DAS_DISCIPLINAS_DISPONIVEIS
	-- DO.IDDISCIPLINA
FROM DISCIPLINAOFERTADA DO 
JOIN DISCIPLINA D ON DO.IDDISCIPLINA = D.ID 
JOIN CURSO C ON C.ID = DO.IDCURSO
WHERE D.STATUS = 'ABERTA' AND DO.ANO = 2018



--4)
SELECT
	 E.TITULO AS ATIVIDADES_NÃO_ENTREGUES,
	 E.STATUS
FROM DISCIPLINAOFERTADA AS DO
INNER JOIN ATIVIDADEVINCULADA AS AV
ON DO.ID = AV.IDDOFERTADA
INNER JOIN ENTREGA AS E 
ON E.IDAVINCULADA = AV.ID
WHERE E.STATUS NOT IN( 'CORRIGIDO' , 'ENTREGUE')


--5)
SELECT
	 E.TITULO AS ATIVIDADES_ENTREGUES,
	 E.STATUS
FROM DISCIPLINAOFERTADA AS DO
INNER JOIN ATIVIDADEVINCULADA AS AV
ON DO.ID = AV.IDDOFERTADA
INNER JOIN ENTREGA AS E 
ON E.IDAVINCULADA = AV.ID
WHERE E.STATUS = ('ENTREGUE')

--6)
SELECT D.NOME AS DISCIPLINA_SEM_PROFESSOR
FROM DISCIPLINAOFERTADA AS DO
INNER JOIN PROFESSOR AS P 
ON P.ID = DO.IDPROFESSOR
INNER JOIN DISCIPLINA AS D
ON DO.IDDISCIPLINA = D.ID
WHERE IDPROFESSOR IS NULL
	   

--7)
SELECT D.NOME,
	   COUNT(S.ID) AS QTDE
FROM DISCIPLINA D  
LEFT JOIN DISCIPLINAOFERTADA DO
ON D.ID = DO.IDDISCIPLINA
LEFT JOIN SOLICITACAOMATRICULA S
ON DO.ID = S.IDDOFERTADA 
GROUP BY D.NOME 
ORDER BY D.NOME 

--8)
SELECT A.NOME, 
       (SELECT EN.NOTA FROM ENTREGA EN JOIN ATIVIDADEVINCULADA ATV ON ATV.ID = EN.IDAVINCULADA WHERE EN.IDALUNO = E.IDALUNO AND ATV.IDATIVIDADE = 1 AND ATV.IDPROFESSOR = AV.IDPROFESSOR) AS AC_1,
       (SELECT EN.NOTA FROM ENTREGA EN JOIN ATIVIDADEVINCULADA ATV ON ATV.ID = EN.IDAVINCULADA WHERE EN.IDALUNO = E.IDALUNO AND ATV.IDATIVIDADE = 2 AND ATV.IDPROFESSOR = AV.IDPROFESSOR) AS AC_2,
	   (SELECT EN.NOTA FROM ENTREGA EN JOIN ATIVIDADEVINCULADA ATV ON ATV.ID = EN.IDAVINCULADA WHERE EN.IDALUNO = E.IDALUNO AND ATV.IDATIVIDADE = 3 AND ATV.IDPROFESSOR = AV.IDPROFESSOR) AS AC_3,
	   (SELECT EN.NOTA FROM ENTREGA EN JOIN ATIVIDADEVINCULADA ATV ON ATV.ID = EN.IDAVINCULADA WHERE EN.IDALUNO = E.IDALUNO AND ATV.IDATIVIDADE = 4 AND ATV.IDPROFESSOR = AV.IDPROFESSOR) AS AC_4,
	   (SELECT EN.NOTA FROM ENTREGA EN JOIN ATIVIDADEVINCULADA ATV ON ATV.ID = EN.IDAVINCULADA WHERE EN.IDALUNO = E.IDALUNO AND ATV.IDATIVIDADE = 5 AND ATV.IDPROFESSOR = AV.IDPROFESSOR) AS AC_5,
       (SELECT EN.NOTA FROM ENTREGA EN JOIN ATIVIDADEVINCULADA ATV ON ATV.ID = EN.IDAVINCULADA WHERE EN.IDALUNO = E.IDALUNO AND ATV.IDATIVIDADE = 6 AND ATV.IDPROFESSOR = AV.IDPROFESSOR) AS AC_6,
	   (SELECT EN.NOTA FROM ENTREGA EN JOIN ATIVIDADEVINCULADA ATV ON ATV.ID = EN.IDAVINCULADA WHERE EN.IDALUNO = E.IDALUNO AND ATV.IDATIVIDADE = 7 AND ATV.IDPROFESSOR = AV.IDPROFESSOR) AS AC_7,
	   (SELECT EN.NOTA FROM ENTREGA EN JOIN ATIVIDADEVINCULADA ATV ON ATV.ID = EN.IDAVINCULADA WHERE EN.IDALUNO = E.IDALUNO AND ATV.IDATIVIDADE = 8 AND ATV.IDPROFESSOR = AV.IDPROFESSOR) AS AC_8,
	   (SELECT EN.NOTA FROM ENTREGA EN JOIN ATIVIDADEVINCULADA ATV ON ATV.ID = EN.IDAVINCULADA WHERE EN.IDALUNO = E.IDALUNO AND ATV.IDATIVIDADE = 9 AND ATV.IDPROFESSOR = AV.IDPROFESSOR) AS AC_9,
	   (SELECT EN.NOTA FROM ENTREGA EN JOIN ATIVIDADEVINCULADA ATV ON ATV.ID = EN.IDAVINCULADA WHERE EN.IDALUNO = E.IDALUNO AND ATV.IDATIVIDADE = 10 AND ATV.IDPROFESSOR = AV.IDPROFESSOR) AS AC_10,

FROM ENTREGA E  
JOIN ATIVIDADEVINCULADA AV ON AV.ID = E.IDAVINCULADA 
JOIN ALUNO A ON E.IDALUNO = A.ID
WHERE AV.IDPROFESSOR = 18
