-- CRIANDO TABELA PROFESSOR
	CREATE TABLE PROFESSOR
	(	
		ID_PROFESSOR INT IDENTITY NOT NULL,
		ID_USUARIO INT NOT NULL,
		EMAIL VARCHAR(30) NOT NULL,
		CELULAR CHAR(11) NOT NULL,
		APELIDO VARCHAR(15) NOT NULL

		CONSTRAINT PK_PROFESSOR PRIMARY KEY (ID_PROFESSOR),
		CONSTRAINT UQ_EMAIL UNIQUE (EMAIL),
		CONSTRAINT UQ_CELULAR UNIQUE (CELULAR)

	);

-- CRIANDO TABELA ENTREGA
	CREATE TABLE ENTREGA
	( 
		ID_ENTREGA INT IDENTITY NOT NULL,
		ID_ALUNO INT NOT NULL,
		ID_ATIVIDADE_VINCULADA INT NOT NULL,
		TITULO VARCHAR(30)NOT NULL,
		RESPOSTA VARCHAR(140) NOT NULL,
		DT_ENTREGA DATETIME NOT NULL DEFAULT (GETDATE()),
		STATUS VARCHAR(30) NOT NULL DEFAULT ('ENTREGUE'),
		ID_PROFESSOR INT,
		NOTA DECIMAL(3,1),
		DT_AVALIACAO DATE,
 		OBS VARCHAR (100),


		CONSTRAINT PK_ENTREGA PRIMARY KEY (ID_ENTREGA),
		CONSTRAINT CK_ENTREGA_STATUS CHECK (STATUS IN ('ENTREGUE', 'CORRIGIDO')),
		CONSTRAINT CK_NOTA CHECK (NOTA >= '0.00' AND NOTA <= '10.00'),

	);

	