CREATE TABLE ALUNO(
	ID INT IDENTITY,
	ID_USUARIO INT,
	NOME VARCHAR(30) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	CELULAR TINYINT  NOT NULL,
	RA INT NOT NULL,
	FOTO VARCHAR(30)
	CONSTRAINT UQ_EMAIL_ALUNO UNIQUE (EMAIL),
	CONSTRAINT UQ_CELULAR_ALUNO UNIQUE (CELULAR),
	CONSTRAINT PK_ID PRIMARY KEY (ID)
	);

CREATE TABLE ATIVIDADE_VINCULADA(
	ID INT IDENTITY,
	ID_ATIVIDADE INT,
	ID_PROFESSOR INT,
	ID_DICIPLINA_OFERTA INT,
	ROTULO VARCHAR(60),
	STATUS VARCHAR(30),
	DTLINICIO_RESPOSTA VARCHAR(100),
	DTFIM_RESPOSTA VARCHAR (100),
	CONSTRAINT ATIVIDADE_VINCULADA_CK_STATUS CHECK (STATUS IN('DISPONIBILIZADA', 'ABERTA', 'FECHADA',
	'ENCERRADA','PRORROGADA'))
	);
	 

	 
 