-- TABELA COORDENADOR

CREATE TABLE COORDENADOR
(
	ID INT IDENTITY NOT NULL,
	ID_USUARIO INT NOT NULL,
	NOME VARCHAR (30) NOT NULL,
	EMAIL VARCHAR (50) NOT NULL,
	CELULAR CHAR (11) NOT NULL,

	CONSTRAINT PK_COORDENARDOR PRIMARY KEY (ID),
	CONSTRAINT UQ_EMAIL UNIQUE (EMAIL),
	CONSTRAINT UQ_CELULAR UNIQUE (CELULAR)

);


-- TABELA ATIVIDADE

CREATE TABLE ATIVIDADE
(
	ID INT IDENTITY NOT NULL,
	TITULO_ATIVIDADE VARCHAR (20) NOT NULL,
	DESCRICAO_ATIVIDADE VARCHAR (100),
	CONTEUDO_ATIVIDADE VARCHAR (100) NOT NULL,
	TIPO_ATIVIDADE VARCHAR (15) NOT NULL,
	EXTRA_ATIVIDADE VARCHAR (100),
	ID_PROFESSOR INT NOT NULL

	CONSTRAINT PK_ATIVIDADE PRIMARY KEY (ID),
	CONSTRAINT UQ_TITULO UNIQUE (TITULO_ATIVIDADE),
	CONSTRAINT CK_TIPO_ATIVIDADE CHECK (TIPO_ATIVIDADE IN ('RESPOSTA ABERTA', 'TESTE'))

);