# Generated by Django 2.0.6 on 2018-10-29 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='disciplinaOfertadaaaaa',
        ),
    ]
